# Generated by Django 3.1.3 on 2020-11-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
