# Generated by Django 3.1.3 on 2020-11-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_prefer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prefer',
        ),
    ]
