# Generated by Django 3.1.3 on 2020-11-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('genre_id', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('origin_title', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=1000)),
                ('poster_path', models.CharField(max_length=500)),
                ('backdrop_path', models.CharField(blank=True, max_length=500, null=True)),
                ('genres', models.ManyToManyField(related_name='genre_movie', to='movies.Genre')),
            ],
        ),
    ]
